name: my-env

channels:
  - conda-forge
  - set3mah

dependencies:
  - cxx-compiler
  - fortran-compiler
  - libblas * *mkl
  - liblapack * *mkl
  - mkl
  - numpy>=1.26
  - cmake
  - python
  - pip
  - setuptools
  - gtest
  - pybind11
  - armadillo >= 12.6
  - carma
  - pytest
  - ninja
