name: my-env

channels:
  - conda-forge
  - set3mah

dependencies:
  - pkg-config
  - libblas * *mkl
  - liblapack * *mkl
  - cmake>=3.30
  - python
  - numpy>=1.24
  - pip
  - setuptools
  - gtest
  - pybind11
  - armadillo >= 12.6
  - carma
  - pytest
  - ninja
  - mkl
